apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
  namespace: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: trainwithshubham/notes-app-k8s
        ports:
        - containerPort: 8000

